feat(discovery service): support multiple search results in discovery service
mnestix/mnestix-browser pull request #26
Opened 2024-07-10 13:01 UTC by pawel-baran-se

Introduce "/viewer/discovery" path with a result table from discovery service

- Add a new endpoint "/viewer/discovery" to display results from the discovery service.
- Visualize the results in a table if the discovery service returns more than one AAS Id.
- Enable user to choose which AAS Id to view in detail from the result table.

2024-07-15 08:55 UTC, NilsXitaso approved these changes

2024-07-15 09:29 UTC, hofermo commented on src/app/[locale]/compare/_components/add-aas/ManualAasAddInput.tsx
>                      severity: 'error',
is this really an error?

2024-07-15 09:36 UTC, hofermo commented on src/app/[locale]/viewer/_components/ManualAasViewerInput.tsx
> +                const aasId = aasIds && aasIds.length === 1 ? aasIds[0] : val;
I believe this is here if `val` is not an asset Id but an AAS ID?
Can you explain that in a comment above somewhere?

2024-07-15 09:37 UTC, hofermo commented on src/app/[locale]/viewer/_components/ManualAasViewerInput.tsx
> +                navigate.push(`/viewer/discovery?aasId=${val}`);
Is `val` an Asset or AAS Id? the discovery only makes sense if it is an asset Id correct?

2024-07-15 09:38 UTC, hofermo commented on src/app/[locale]/viewer/discovery/_components/DiscoveryListView.tsx
> +    const aasId = searchParams.get('aasId');
this is an assetId if I am not mistaken

2024-07-15 09:40 UTC, hofermo commented on src/lib/searchUtilActions/search.ts
>   */
It takes an AssetId or an AAS ID?

2024-07-15 09:40 UTC, hofermo commented on src/lib/searchUtilActions/search.ts
> +export async function handleAasDiscoverySearch(searchAasId: string): Promise<string[] | null> {
I think this might be a copy paste error, the discovery takes an asset id not an aas id

2024-07-15 09:41 UTC, hofermo commented on src/lib/util/checkAasAvailabilityUtil.ts
> +    const localRepoUrl = url ? `${url}/shells/${b64_aasId}` : '';
can we use a api from api.ts here?

2024-07-15 09:42 UTC, hofermo commented on src/lib/util/checkAasAvailabilityUtil.ts
> +    const response = await fetch(localRepoUrl, { method: 'HEAD' });
do we want to handle errors that can occur here?

2024-07-15 09:46 UTC, hofermo requested changes
see my comments

2024-07-17 08:20 UTC, hofermo approved these changes

2024-07-18 07:16 UTC, merged