feat(submodel registry): Establish submodel registry
mnestix/mnestix-browser pull request #29
Opened 2024-07-15 08:10 UTC by NilsXitaso

2024-07-15 09:19 UTC, hofermo commented on src/app/[locale]/viewer/_components/SubmodelsOverviewCard.tsx
> +            const metadata = await submodelClient.getSubmodelMetaDataById(id);
Unsure if my PR #30 will change this as well, please let us check this when you merge

2024-07-15 09:20 UTC, hofermo commented on src/app/[locale]/viewer/_components/SubmodelsOverviewCard.tsx
> +        }
Why no try catch as below?

2024-07-15 09:25 UTC, hofermo commented on src/app/[locale]/viewer/_components/SubmodelsOverviewCard.tsx
> +                    // expexted behaviour if submodel registry is not available or submodel is not found there
A catch with no logic?

2024-07-15 09:27 UTC, hofermo requested changes

2024-07-15 09:27 UTC, hofermo commented on src/app/[locale]/viewer/_components/submodel-elements/entity-component/RelationShipDetailsDialog.tsx
> +                    } catch (e) {
same here

2024-07-15 09:46 UTC, hofermo requested changes
see my comments

2024-07-16 06:57 UTC, hofermo approved these changes

2024-07-17 07:42 UTC, GailMelanie approved these changes

2024-07-17 08:25 UTC, merged