fix(configurationShellApi): change default value for "use_authentication" to true
mnestix/mnestix-browser pull request #31
Opened 2024-07-15 12:41 UTC by pawel-baran-se

- Pass access token to the request

2024-07-16 05:54 UTC, NilsXitaso approved these changes

2024-07-17 07:48 UTC, GailMelanie commented on src/lib/api/configuration-shell-api/configurationShellApi.ts
> +        use_authentication: boolean = true,
In our Readme, we define the authentication default value as "false" (see AUTHENTICATION_FEATURE_FLAG). Why do we need this change here?

2024-07-17 07:53 UTC, GailMelanie requested changes
See comment

2024-07-17 10:46 UTC, GailMelanie commented on src/lib/api/configuration-shell-api/configurationShellApi.ts
> +        use_authentication: boolean = true,
adapted the usage of the feature flag

2024-07-17 10:48 UTC, hofermo approved these changes

2024-07-17 10:51 UTC, GailMelanie approved these changes

2024-07-17 11:01 UTC, merged