bugfix(thumbnail): fix standard thumbnail
mnestix/mnestix-browser pull request #85
Opened 2024-09-10 08:55 UTC by NilsXitaso

# Description

Please include a summary of the changes and link the related github issue.
Please include relevant motivation and context.

Fixes # (Issue)

## Type of change

Please delete options that are not relevant.

-   [ ] Minor change (non-breaking change, e.g. documentation adaption)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)

# Checklist:

-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix or my feature works
-   [ ] New and existing tests pass locally with my changes
-   [ ] My changes contain no console logs

2024-09-11 11:54 UTC, XAndreJentzsch approved these changes

2024-09-12 14:09 UTC, Xmilofranke requested changes
Two more points in addition to some images false not being displayed: 

1. In the compare view, the placeholder images are clickable
2. In the aas view, there should not be any picture displayed if none was provided. The placeholder should only be shown there, if the provided image couldn't be loaded.

2024-09-12 14:09 UTC, Xmilofranke commented on src/app/[locale]/viewer/_components/AASOverviewCard.tsx
> +                                <StyledImage src={productImageUrl} onErrorCapture={handleError} />
Not sure, when the `onErrorCapture` is triggered, but right now it sometimes prevents the image from being loaded even if it should be loaded. 
(See this test aas: https://wgrp.biz/aas/xNBLy1C and all AAS in the Compare view)

2024-09-20 09:30 UTC, Xmilofranke approved these changes

2024-09-20 10:25 UTC, GailMelanie approved these changes

2024-09-20 10:33 UTC, merged